services:
  - type: web
    name: civic-services
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: BUILD_VERSION
        value: "2024.02.1"
      - key: DB_HOST
        fromDatabase:
          name: civic-services-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: civic-services-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: civic-services-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: civic-services-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: civic-services-db
          property: password
      - key: ADMIN_PASSWORD
        value: "meow@1234"

databases:
  - name: civic-services-db
    plan: free
    databaseName: civic_services
    ipAllowList: []
